Place `%options_configure` after `%configure` instead of `%autogen`
```
│S│ + /usr/bin/bash ./autogen.sh --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --build=x86_64-aerynos-linux --host=x86_64-aerynos-linux --libdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --libexecdir=/usr/lib/emacs
│S│ ./autogen.sh: --prefix=/usr: unknown argument
Error: build: container: exited with failure: run: build recipe: failed with status code 1
error: Recipe `_build` failed on line 19 with exit code 1
```
should fix this